### ISSUE TITLE
Bootloader

### ISSUE THREAD

**Issue by dvv** [ClusterM/clunet#1]
Привет!

Замечательный проект. Чистый код.

Пара вопросов:
- открыт ли код bootloaderа? если нет, можно ли иметь hex для atmega328p?
- не совместим ли clunet c one-wire протоколом http://jtxp.org/tech/tinysafeboot_en.htm#protokolle

Спасибо,
--Владимир

**Comment by zhdan88vadim** [comment]
> рвоначально превышало 1200 октетов, удалось ужать. Если отработает, пришлю обезжиривающий патчик.

могли бы выложить код для 328p ? Мне и думаю другим было бы инересно)

**Comment by UncleJey** [comment]
Господа! У меня план!
1. Отключаем внешнюю камеру видеонаблюдения.
2. используя этот кабель подключаемся к домашней сети кластера
3. выкачиваем грязные секреты
4. заботливо подсаживаем троянчика

зачем это нужно я ещё не придумал, но наверняка пригодится!
